language: ruby

sudo: false

rvm:
  - 2.3.3
  - 2.4.0

gemfile:
  - test/gemfiles/Gemfile-AR4.2
  - test/gemfiles/Gemfile-AR5.0

matrix:
  allow_failures:
    - rvm: 2.4.0

script: rake test

branches:
  only:
    - master
